[package]
name = "dndui"
version = "0.1.0"
authors = ["Theoreticallyhugo <me@theoreticallyhugo.com>"]
license = "MIT"
edition = "2021"

[dependencies]
chrono = "0.4.34"
crossterm = "0.27.0"
machine-info = "1.0.9"
ratatui = "0.26.0"
